name: Fetch Figma Design JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write  

jobs:
  fetch-figma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Figma JSON
        run: |
          curl -H "X-Figma-Token: ${{ secrets.FIGMA_TOKEN }}" \
            https://api.figma.com/v1/files/4CzCOQynX1F6VCEsZMZpDi \
            -o figma_design.json

      - name: Commit Figma JSON
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add figma_design.json
          git commit -m "자동 저장: Figma JSON" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
